name: Continuous Live Stream

on:
  workflow_dispatch:
    inputs:
      song_url:
        description: 'YouTube Video Link'
        required: true
        default: 'https://youtu.be/HclbhIm6tZU'

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install System Dependencies & Latest yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          python3 -m pip install --upgrade --force-reinstall yt-dlp

      - name: Save Cookies Data
        env:
          COOKIES_DATA: ${{ secrets.YT_COOKIES }}
        run: |
          echo "$COOKIES_DATA" > cookies.txt

      - name: Download Video to Cloud Storage
        run: |
          yt-dlp --cookies cookies.txt --extractor-args "youtube:player_client=ios" -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -o "video.mp4" "${{ github.event.inputs.song_url }}"

      - name: Stream Local File 24/7
        run: |
          ffmpeg -re -stream_loop -1 -i video.mp4 \
            -c:v libx264 -preset ultrafast -b:v 2500k -maxrate 2500k -bufsize 5000k -g 50 \
            -c:a aac -b:a 128k -ar 44100 \
            -f flv "rtmp://a.rtmp.youtube.com/live2/b2fx-28zj-rs4u-6wsa-79k8"
